### ISSUE TITLE
请问你编FastDDS为UE插件的时候遇到这些报错了吗？

### ISSUE THREAD

**Issue by logic88** [GlambertsQY/FastDDSUEPlugin#1]
1>libfastddsd-3.0.lib(Time_t.cpp.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(Time_t.cpp.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(Time_t.cpp.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(Time_t.cpp.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(DomainParticipantFactory.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(DomainParticipantFactory.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(Log.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(Log.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(DomainParticipant.cpp.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(DomainParticipant.cpp.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(DynamicDataFactory.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(DynamicDataFactory.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(DynamicTypeBuilderFactory.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)
1>libfastddsd-3.0.lib(DynamicTypeBuilderFactory.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(SharedPCH.Core.NonOptimized.RTTI.Cpp17.InclOrderUnreal5_0.h.obj 中)

**Comment by logic88** [comment]
这是我编好FastDDS静态库后，在UE插件中引入编好的FastDDS静态库时报的错，想请教一下你怎么解决的

**Comment by GlambertsQY** [comment]
用VS的话需要设置这些参数吧
![image](https://github.com/user-attachments/assets/e7104168-8b0e-4151-87f8-e77301dbb237)
